/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.przelicznik_jednostek;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Dzemor
 */
public class Przelicznik_jednostek extends javax.swing.JFrame {

    /**
     * Creates new form Przelicznik_jednostek
     */
    public Przelicznik_jednostek(){
        initComponents();
        
    }
    private void pokazhistorie(){
        try{
            String ms_text = "";
            Scanner sc = new Scanner(fileDzialania);
             while(sc.hasNext()){
                ms_text = ms_text+sc.nextLine()+"<br/>";
            }
            JOptionPane.showMessageDialog(null,"<html>Ostatnie działania:<br>"+ms_text+"</html>");
        }catch(FileNotFoundException ex){
            System.out.println("Blad: "+ex.toString());
        }
    }
    private void zapiszdzialanie(){
        try{
            FileWriter fw = new FileWriter(fileDzialania, true);
            fw.write(ms_rodzajDzialania+";"+ms_WprowadzonaLiczba+" "+ms_Jednostka1+";"+ms_Wynik+" "+ms_Jednostka2+"\n");
            fw.close();
        }catch (IOException ex) {
            System.out.println("Blad: "+ex.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_jTabbedPane = new javax.swing.JTabbedPane();
        ms_jPanelTemp = new javax.swing.JPanel();
        ms_jLabeTemp = new javax.swing.JLabel();
        ms_jComboBoxTemp = new javax.swing.JComboBox<>();
        ms_jTextFieldInputTemp = new javax.swing.JTextField();
        ms_jLabelInputTemp = new javax.swing.JLabel();
        ms_jLabelArrowTemp = new javax.swing.JLabel();
        ms_jTextFieldOutputTemp = new javax.swing.JTextField();
        ms_jLabelOutputTemp = new javax.swing.JLabel();
        ms_jButtonTemp = new javax.swing.JButton();
        ms_jPanelDistance = new javax.swing.JPanel();
        ms_jLabelDistance = new javax.swing.JLabel();
        ms_jComboBoxDistance = new javax.swing.JComboBox<>();
        ms_jTextFieldInputDistance = new javax.swing.JTextField();
        ms_jLabelInputDistance = new javax.swing.JLabel();
        ms_jLabelArrowDistance = new javax.swing.JLabel();
        ms_jTextFieldOutputDistance = new javax.swing.JTextField();
        ms_jLabelOutputDistance = new javax.swing.JLabel();
        ms_jButtonDistance = new javax.swing.JButton();
        ms_jMenuBar = new javax.swing.JMenuBar();
        ms_jMenuFile = new javax.swing.JMenu();
        ms_jMenuItemHistory = new javax.swing.JMenuItem();
        ms_jMenuItemExit = new javax.swing.JMenuItem();
        ms_jMenuAbout = new javax.swing.JMenu();
        ms_jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Przelicznik jednostek");
        setResizable(false);

        ms_jLabeTemp.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ms_jLabeTemp.setText("Kalkulator temperatury");

        ms_jComboBoxTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proszę wybrać jednostki do obliczeń", "C ----> F", "F ----> C" }));
        ms_jComboBoxTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jComboBoxTempActionPerformed(evt);
            }
        });

        ms_jTextFieldInputTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jTextFieldInputTempActionPerformed(evt);
            }
        });

        ms_jLabelInputTemp.setText("Wejśćie");

        ms_jLabelArrowTemp.setText("---->");

        ms_jLabelOutputTemp.setText("Wyjście");

        ms_jButtonTemp.setText("Oblicz");
        ms_jButtonTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ms_jPanelTempLayout = new javax.swing.GroupLayout(ms_jPanelTemp);
        ms_jPanelTemp.setLayout(ms_jPanelTempLayout);
        ms_jPanelTempLayout.setHorizontalGroup(
            ms_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelTempLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(ms_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelTempLayout.createSequentialGroup()
                        .addComponent(ms_jComboBoxTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ms_jTextFieldInputTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ms_jLabelArrowTemp)
                        .addGap(18, 18, 18)
                        .addComponent(ms_jTextFieldOutputTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ms_jButtonTemp)
                        .addContainerGap(173, Short.MAX_VALUE))
                    .addGroup(ms_jPanelTempLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ms_jLabelInputTemp)
                        .addGap(146, 146, 146)
                        .addComponent(ms_jLabelOutputTemp)
                        .addGap(282, 282, 282))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelTempLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ms_jLabeTemp)
                .addGap(153, 153, 153))
        );
        ms_jPanelTempLayout.setVerticalGroup(
            ms_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelTempLayout.createSequentialGroup()
                .addComponent(ms_jLabeTemp)
                .addGap(87, 87, 87)
                .addGroup(ms_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jLabelOutputTemp)
                    .addComponent(ms_jLabelInputTemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ms_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ms_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_jComboBoxTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ms_jTextFieldInputTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ms_jLabelArrowTemp))
                    .addGroup(ms_jPanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_jTextFieldOutputTemp)
                        .addComponent(ms_jButtonTemp)))
                .addGap(0, 163, Short.MAX_VALUE))
        );

        ms_jTabbedPane.addTab("Temperatura", ms_jPanelTemp);

        ms_jLabelDistance.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ms_jLabelDistance.setText("Kalkulator odległośći");

        ms_jComboBoxDistance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proszę wybrać jednostki do obliczeń", "m ----> Km", "Km ----> m", "mile ----> Km", "Km ----> mile" }));

        ms_jTextFieldInputDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jTextFieldInputDistanceActionPerformed(evt);
            }
        });

        ms_jLabelInputDistance.setText("Wejśćie");

        ms_jLabelArrowDistance.setText("---->");

        ms_jLabelOutputDistance.setText("Wyjście");

        ms_jButtonDistance.setText("Oblicz");
        ms_jButtonDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonDistanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ms_jPanelDistanceLayout = new javax.swing.GroupLayout(ms_jPanelDistance);
        ms_jPanelDistance.setLayout(ms_jPanelDistanceLayout);
        ms_jPanelDistanceLayout.setHorizontalGroup(
            ms_jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelDistanceLayout.createSequentialGroup()
                .addGroup(ms_jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelDistanceLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(ms_jLabelDistance))
                    .addGroup(ms_jPanelDistanceLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(ms_jLabelInputDistance)
                        .addGap(159, 159, 159)
                        .addComponent(ms_jLabelOutputDistance))
                    .addGroup(ms_jPanelDistanceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ms_jComboBoxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ms_jTextFieldInputDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_jLabelArrowDistance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_jTextFieldOutputDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ms_jButtonDistance)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        ms_jPanelDistanceLayout.setVerticalGroup(
            ms_jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelDistanceLayout.createSequentialGroup()
                .addComponent(ms_jLabelDistance)
                .addGap(87, 87, 87)
                .addGroup(ms_jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jLabelInputDistance)
                    .addComponent(ms_jLabelOutputDistance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ms_jPanelDistanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jComboBoxDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jTextFieldInputDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jLabelArrowDistance)
                    .addComponent(ms_jTextFieldOutputDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jButtonDistance))
                .addGap(0, 158, Short.MAX_VALUE))
        );

        ms_jTabbedPane.addTab("Odległość", ms_jPanelDistance);

        ms_jMenuFile.setText("Plik");

        ms_jMenuItemHistory.setText("Pokaż historię");
        ms_jMenuItemHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemHistoryActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemHistory);

        ms_jMenuItemExit.setText("Zamknij");
        ms_jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemExitActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemExit);

        ms_jMenuBar.add(ms_jMenuFile);

        ms_jMenuAbout.setText("O programie");

        ms_jMenuItemAbout.setText("O programie");
        ms_jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemAboutActionPerformed(evt);
            }
        });
        ms_jMenuAbout.add(ms_jMenuItemAbout);

        ms_jMenuBar.add(ms_jMenuAbout);

        setJMenuBar(ms_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ms_jMenuItemExitActionPerformed

    private void ms_jTextFieldInputDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jTextFieldInputDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jTextFieldInputDistanceActionPerformed

    private void ms_jTextFieldInputTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jTextFieldInputTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jTextFieldInputTempActionPerformed

    private void ms_jComboBoxTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jComboBoxTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jComboBoxTempActionPerformed

    private void ms_jButtonTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonTempActionPerformed
       ms_jTextFieldOutputTemp.setText("");
       ms_WybranaJednostka = ms_jComboBoxTemp.getSelectedIndex();
       System.out.print(ms_WybranaJednostka);
       ms_rodzajDzialania = "t";
       switch(ms_WybranaJednostka){
           case 1:
               ms_Jednostka1 = "C";
               ms_Jednostka2 = "F";
               ms_WprowadzonaLiczba = Integer.parseInt(ms_jTextFieldInputTemp.getText());
               double ms_Wynik = (ms_WprowadzonaLiczba*1.8)+32;
               ms_jTextFieldOutputTemp.setText(String.valueOf(ms_Wynik));
               zapiszdzialanie();
               break;
           case 2:
               ms_Jednostka1 = "F";
               ms_Jednostka2 = "C";
               ms_WprowadzonaLiczba = Integer.parseInt(ms_jTextFieldInputTemp.getText());
               ms_Wynik = (ms_WprowadzonaLiczba-32)/1.8;
               ms_jTextFieldOutputTemp.setText(String.valueOf(ms_Wynik));
               zapiszdzialanie();
               break;
           default:
               System.out.println("Nie ma takie opcji!!");
        }
    }//GEN-LAST:event_ms_jButtonTempActionPerformed

    private void ms_jButtonDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonDistanceActionPerformed
       ms_jTextFieldOutputDistance.setText("");
       ms_WybranaJednostka = ms_jComboBoxDistance.getSelectedIndex();
       System.out.println(ms_WybranaJednostka);
       ms_rodzajDzialania = "o";
       switch(ms_WybranaJednostka){
           case 1:
               ms_Jednostka1 = "m";
               ms_Jednostka2 = "Km";
               ms_WprowadzonaLiczba = Integer.parseInt(ms_jTextFieldInputDistance.getText());
               ms_Wynik = ms_WprowadzonaLiczba / 1000;
               ms_jTextFieldOutputDistance.setText(String.valueOf(ms_Wynik));
               zapiszdzialanie();
               break;
           case 2:
               ms_Jednostka1 = "Km";
               ms_Jednostka2 = "m";
               ms_WprowadzonaLiczba = Integer.parseInt(ms_jTextFieldInputDistance.getText());
               ms_Wynik = ms_WprowadzonaLiczba * 1000;
               ms_jTextFieldOutputDistance.setText(String.valueOf(ms_Wynik));
               zapiszdzialanie();
               break;
           case 3:
               ms_Jednostka1 = "mil";
               ms_Jednostka2 = "Km";
               ms_WprowadzonaLiczba = Integer.parseInt(ms_jTextFieldInputDistance.getText());
               ms_Wynik = ms_WprowadzonaLiczba * 1.61;
               ms_jTextFieldOutputDistance.setText(String.valueOf(ms_Wynik));
               zapiszdzialanie();
               break;
           case 4:
               ms_Jednostka1 = "Km";
               ms_Jednostka2 = "mil";
               ms_WprowadzonaLiczba = Integer.parseInt(ms_jTextFieldInputDistance.getText());
               ms_Wynik = ms_WprowadzonaLiczba * 0.62137;
               ms_jTextFieldOutputDistance.setText(String.valueOf(ms_Wynik));
               zapiszdzialanie();
               break;
           default:
               System.out.println("Nie ma takie opcji!!");
        }
    }//GEN-LAST:event_ms_jButtonDistanceActionPerformed

    private void ms_jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(null,"Wykonał Mateusz Suchocki z 2 PTN");
    }//GEN-LAST:event_ms_jMenuItemAboutActionPerformed

    private void ms_jMenuItemHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemHistoryActionPerformed
        pokazhistorie();
    }//GEN-LAST:event_ms_jMenuItemHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Przelicznik_jednostek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Przelicznik_jednostek().setVisible(true);
            }
        });
    }
    double ms_Wynik;
    int ms_WybranaJednostka;
    int ms_WprowadzonaLiczba;
    String ms_Jednostka1;
    String ms_Jednostka2;
    String ms_rodzajDzialania;
    File fileDzialania  = new File("dzialania.txt");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ms_jButtonDistance;
    private javax.swing.JButton ms_jButtonTemp;
    private javax.swing.JComboBox<String> ms_jComboBoxDistance;
    private javax.swing.JComboBox<String> ms_jComboBoxTemp;
    private javax.swing.JLabel ms_jLabeTemp;
    private javax.swing.JLabel ms_jLabelArrowDistance;
    private javax.swing.JLabel ms_jLabelArrowTemp;
    private javax.swing.JLabel ms_jLabelDistance;
    private javax.swing.JLabel ms_jLabelInputDistance;
    private javax.swing.JLabel ms_jLabelInputTemp;
    private javax.swing.JLabel ms_jLabelOutputDistance;
    private javax.swing.JLabel ms_jLabelOutputTemp;
    private javax.swing.JMenu ms_jMenuAbout;
    private javax.swing.JMenuBar ms_jMenuBar;
    private javax.swing.JMenu ms_jMenuFile;
    private javax.swing.JMenuItem ms_jMenuItemAbout;
    private javax.swing.JMenuItem ms_jMenuItemExit;
    private javax.swing.JMenuItem ms_jMenuItemHistory;
    private javax.swing.JPanel ms_jPanelDistance;
    private javax.swing.JPanel ms_jPanelTemp;
    private javax.swing.JTabbedPane ms_jTabbedPane;
    private javax.swing.JTextField ms_jTextFieldInputDistance;
    private javax.swing.JTextField ms_jTextFieldInputTemp;
    private javax.swing.JTextField ms_jTextFieldOutputDistance;
    private javax.swing.JTextField ms_jTextFieldOutputTemp;
    // End of variables declaration//GEN-END:variables
}
