/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.formularzdaneosobowe;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;

/**
 *
 * @author Dzemor
 */
public class FormularzDaneOsobowe extends javax.swing.JFrame {

    /**
     * Creates new form FormularzDaneOsobowe
     */
    public FormularzDaneOsobowe() {
        initComponents();
        addKeyListnerToHeigth();
        addKeyListnerToUsername();
        addKeyListnerToWeigth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_jPanelMain = new javax.swing.JPanel();
        ms_jTextFieldUsername = new javax.swing.JTextField();
        ms_jButtonSave = new javax.swing.JButton();
        ms_jLabelUsername = new javax.swing.JLabel();
        ms_jLabeEmaill = new javax.swing.JLabel();
        ms_jTextFieldEmail = new javax.swing.JTextField();
        ms_jDateChooserDate = new com.toedter.calendar.JDateChooser();
        ms_jLabelWeigth = new javax.swing.JLabel();
        ms_jTextFieldWeigth = new javax.swing.JTextField();
        ms_jLabelHeigth = new javax.swing.JLabel();
        ms_TextFieldHeigth = new javax.swing.JTextField();
        ms_jLabelDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formularz");
        setResizable(false);

        ms_jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        ms_jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jTextFieldUsernameActionPerformed(evt);
            }
        });

        ms_jButtonSave.setText("Zapisz");
        ms_jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonSaveActionPerformed(evt);
            }
        });

        ms_jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelUsername.setText("Username");

        ms_jLabeEmaill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabeEmaill.setText("Email");

        ms_jDateChooserDate.setDateFormatString("d-MM-y");

        ms_jLabelWeigth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelWeigth.setText("Waga");

        ms_jLabelHeigth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelHeigth.setText("Wzrost");

        ms_jLabelDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelDate.setText("Data urodzenia");

        javax.swing.GroupLayout ms_jPanelMainLayout = new javax.swing.GroupLayout(ms_jPanelMain);
        ms_jPanelMain.setLayout(ms_jPanelMainLayout);
        ms_jPanelMainLayout.setHorizontalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelMainLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ms_jButtonSave))
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ms_jLabeEmaill))
                            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ms_jLabelUsername)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ms_jTextFieldUsername)
                            .addComponent(ms_jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                .addComponent(ms_jLabelWeigth)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ms_jTextFieldWeigth)))
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                .addComponent(ms_jLabelHeigth)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ms_TextFieldHeigth)))
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                                .addComponent(ms_jLabelDate)
                                .addGap(0, 388, Short.MAX_VALUE))
                            .addComponent(ms_jDateChooserDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        ms_jPanelMainLayout.setVerticalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ms_jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jLabeEmaill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jLabelWeigth)
                .addGap(18, 18, 18)
                .addComponent(ms_jTextFieldWeigth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jLabelHeigth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_TextFieldHeigth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jLabelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jDateChooserDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(ms_jButtonSave))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonSaveActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("d-MM-y");
        boolean tempUsername = false;
        int user = ms_jTextFieldUsername.getText().length();
        if(user >= 2){
           tempUsername = true;
        }else{
           tempUsername = false;
        }
        boolean tempWeigth = false;
        int weigth = ms_jTextFieldWeigth.getText().length();
        if(weigth >= 2){
           tempWeigth = true;
        }else{
           tempWeigth = false;
        }
        boolean tempHeigth = false;
        int heigth = ms_TextFieldHeigth.getText().length();
        if(heigth >= 2){
           tempHeigth = true;
        }else{
           tempHeigth = false;
        }
        String temp = ms_jTextFieldEmail.getText();
        String [] splitted = temp.split("@");
        boolean emai = false;
        if(temp.contains("@")&&temp.contains(".")){
            if(splitted[0].length() >=1 && splitted[1].length() >= 1){
               emai = true;
            }else{
               emai = false;
            }
        }else
        {
            emai = false;
        }
        if(tempHeigth == true && tempWeigth == true && emai == true && tempUsername == true){
            FileUtils fu = new FileUtils();
            String text = ms_jTextFieldUsername.getText()+";"+ms_jTextFieldEmail.getText()+";"+ms_jTextFieldWeigth.getText()+";"+ms_TextFieldHeigth.getText()+";"+sdf.format(ms_jDateChooserDate.getDate());
            fu.saveToFIle(text);
        }else{
            System.out.println("Cos tu nie gra");
        }
    }//GEN-LAST:event_ms_jButtonSaveActionPerformed
    private void addKeyListnerToUsername(){
        ms_jTextFieldUsername.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                String temp = ms_jTextFieldUsername.getText();
                if(ch == KeyEvent.VK_BACK_SPACE || ch >= 65 && ch <= 90 || ch >= 97 && ch <= 122){
                    ms_jTextFieldUsername.setEditable(true);
                    if(temp.length() <= 20 || ch == KeyEvent.VK_BACK_SPACE){
                        ms_jTextFieldUsername.setEditable(true);
                    }else{
                        ms_jTextFieldUsername.setEditable(false);
                    }
                }else{
                    ms_jTextFieldUsername.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
    private void addKeyListnerToWeigth(){
        ms_jTextFieldWeigth.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                String temp = ms_jTextFieldWeigth.getText();
                if(ch == KeyEvent.VK_BACK_SPACE || ch >= 48 && ch <= 57){
                    ms_jTextFieldWeigth.setEditable(true);
                    if(temp.length() <= 3 || ch == KeyEvent.VK_BACK_SPACE){
                        ms_jTextFieldWeigth.setEditable(true);
                    }else{
                        ms_jTextFieldWeigth.setEditable(false);
                    }
                }else{
                    ms_jTextFieldWeigth.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
    private void addKeyListnerToHeigth(){
        ms_TextFieldHeigth.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                String temp = ms_TextFieldHeigth.getText();
                if(ch == KeyEvent.VK_BACK_SPACE || ch >= 48 && ch <= 57){
                    ms_TextFieldHeigth.setEditable(true);
                    if(temp.length() <= 3 || ch == KeyEvent.VK_BACK_SPACE){
                        ms_TextFieldHeigth.setEditable(true);
                    }else{
                        ms_TextFieldHeigth.setEditable(false);
                    }
                }else{
                    ms_TextFieldHeigth.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
    private void ms_jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jTextFieldUsernameActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularzDaneOsobowe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularzDaneOsobowe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularzDaneOsobowe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularzDaneOsobowe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularzDaneOsobowe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ms_TextFieldHeigth;
    private javax.swing.JButton ms_jButtonSave;
    private com.toedter.calendar.JDateChooser ms_jDateChooserDate;
    private javax.swing.JLabel ms_jLabeEmaill;
    private javax.swing.JLabel ms_jLabelDate;
    private javax.swing.JLabel ms_jLabelHeigth;
    private javax.swing.JLabel ms_jLabelUsername;
    private javax.swing.JLabel ms_jLabelWeigth;
    private javax.swing.JPanel ms_jPanelMain;
    private javax.swing.JTextField ms_jTextFieldEmail;
    private javax.swing.JTextField ms_jTextFieldUsername;
    private javax.swing.JTextField ms_jTextFieldWeigth;
    // End of variables declaration//GEN-END:variables
}
