/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sprawdzian_22_03_2021;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Dzemor
 */
public class sprawdzian_22_03_2021 extends javax.swing.JFrame {

    /**
     * Creates new form sprawdzian_22_03_2021
     */
    public sprawdzian_22_03_2021() {
        initComponents();
        addKeyListnertomodel();
        addKeyListenertoPartial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_jPanelMain = new javax.swing.JPanel();
        ms_jLabelSerialNumber = new javax.swing.JLabel();
        ms_jLabelModel = new javax.swing.JLabel();
        ms_jLabelPartialNumber = new javax.swing.JLabel();
        ms_jTextFieldModel = new javax.swing.JTextField();
        ms_jTextFieldPartialNumber = new javax.swing.JTextField();
        ms_jToggleButtonSave = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        ms_jMenuFile = new javax.swing.JMenu();
        ms_jMenuItemSave = new javax.swing.JMenuItem();
        ms_jMenuItemClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mateusz_suchocki");
        setResizable(false);

        ms_jPanelMain.setBackground(new java.awt.Color(204, 255, 204));
        ms_jPanelMain.setForeground(new java.awt.Color(255, 255, 255));

        ms_jLabelSerialNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ms_jLabelSerialNumber.setText("Nr seryjny urządzenia");

        ms_jLabelModel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelModel.setText("Znak modelu");

        ms_jLabelPartialNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelPartialNumber.setText("Nr parti");

        ms_jTextFieldModel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ms_jTextFieldModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jTextFieldModelActionPerformed(evt);
            }
        });

        ms_jTextFieldPartialNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ms_jToggleButtonSave.setText("Zapisz");
        ms_jToggleButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jToggleButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ms_jPanelMainLayout = new javax.swing.GroupLayout(ms_jPanelMain);
        ms_jPanelMain.setLayout(ms_jPanelMainLayout);
        ms_jPanelMainLayout.setHorizontalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_jLabelSerialNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelMainLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ms_jLabelModel)
                    .addComponent(ms_jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addComponent(ms_jToggleButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelMainLayout.createSequentialGroup()
                        .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ms_jLabelPartialNumber)
                            .addComponent(ms_jTextFieldPartialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        ms_jPanelMainLayout.setVerticalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(ms_jLabelSerialNumber)
                .addGap(38, 38, 38)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jLabelModel)
                    .addComponent(ms_jLabelPartialNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jTextFieldPartialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ms_jToggleButtonSave)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        ms_jMenuFile.setText("Plik");

        ms_jMenuItemSave.setText("Zapisz");
        ms_jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemSaveActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemSave);

        ms_jMenuItemClose.setText("Zamknji");
        ms_jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemCloseActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemClose);

        jMenuBar1.add(ms_jMenuFile);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addKeyListenertoPartial(){
        ms_jTextFieldPartialNumber.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                    if(ch == KeyEvent.VK_BACK_SPACE || ch >= '0' && ch <= '9' || ch == KeyEvent.VK_PERIOD){
                        ms_jTextFieldPartialNumber.setEditable(true);
                    }else{
                    ms_jTextFieldPartialNumber.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    private void zapisz(){
        try{
            FileWriter fw = new FileWriter(file, true);
            fw.write(ms_jTextFieldPartialNumber.getText()+" - "+ms_jTextFieldModel.getText());
            fw.close();
        }catch (IOException ex) {
            System.out.println("Blad: "+ex.toString());
        }
    }
    private void ms_jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ms_jMenuItemCloseActionPerformed

    private void ms_jTextFieldModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jTextFieldModelActionPerformed
        
    }//GEN-LAST:event_ms_jTextFieldModelActionPerformed

    private void ms_jToggleButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jToggleButtonSaveActionPerformed
        zapisz();
    }//GEN-LAST:event_ms_jToggleButtonSaveActionPerformed

    private void ms_jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemSaveActionPerformed
        zapisz();
    }//GEN-LAST:event_ms_jMenuItemSaveActionPerformed
    
    private void addKeyListnertomodel(){
        ms_jTextFieldModel.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch == KeyEvent.VK_BACK_SPACE || ch=='p' ||ch=='o' ||ch=='r' ||ch=='s' ||ch=='t' ||ch=='u'){
                    ms_jTextFieldModel.setEditable(true);
                }else{
                ms_jTextFieldModel.setEditable(false);
            }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
              
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sprawdzian_22_03_2021.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sprawdzian_22_03_2021.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sprawdzian_22_03_2021.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sprawdzian_22_03_2021.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sprawdzian_22_03_2021().setVisible(true);
            }
        });
    }
    File file  = new File("mateusz_suchocki.txt");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel ms_jLabelModel;
    private javax.swing.JLabel ms_jLabelPartialNumber;
    private javax.swing.JLabel ms_jLabelSerialNumber;
    private javax.swing.JMenu ms_jMenuFile;
    private javax.swing.JMenuItem ms_jMenuItemClose;
    private javax.swing.JMenuItem ms_jMenuItemSave;
    private javax.swing.JPanel ms_jPanelMain;
    private javax.swing.JTextField ms_jTextFieldModel;
    private javax.swing.JTextField ms_jTextFieldPartialNumber;
    private javax.swing.JToggleButton ms_jToggleButtonSave;
    // End of variables declaration//GEN-END:variables
}
