/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lista_zakupow;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Savepoint;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dzemor
 */
public class Lista_zakupow extends javax.swing.JFrame {

    /**
     * Creates new form Lista_zakupow
     */
    public Lista_zakupow() {
        initComponents();
        final String ARTICLE_FILE = "article_type.csv";
        FileUtils fu = new  FileUtils();
        ms_jTextAreaTodayShopping.setText(fu.readFromFile());
        addKeyListnerToWhatDidYouBought();
        addKeyListnerToInsertValue();
        addKeyListnerToInsertDate();
        addtoolTipsToElements();
        filljCBProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_jTabbedPaneMain = new javax.swing.JTabbedPane();
        ms_jPanelInsert = new javax.swing.JPanel();
        ms_jLabelInsertWhatDidYouBought = new javax.swing.JLabel();
        ms_jTextFieldInsertWhatDidYouBought = new javax.swing.JTextField();
        ms_jLabelInsertValue = new javax.swing.JLabel();
        ms_jTextFieldInsertValue = new javax.swing.JTextField();
        ms_jLabelBoughtType = new javax.swing.JLabel();
        ms_jComboBoxBoughtType = new javax.swing.JComboBox<>();
        ms_jLabelDateBought = new javax.swing.JLabel();
        ms_jTextFieldDateBought = new javax.swing.JTextField();
        ms_jLabelTodayShopping = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ms_jTextAreaTodayShopping = new javax.swing.JTextArea();
        ms_jLabelTodayCost = new javax.swing.JLabel();
        ms_jLabelWeekCost = new javax.swing.JLabel();
        ms_jTextFieldTodayCost = new javax.swing.JTextField();
        ms_jTextFieldWeekCost = new javax.swing.JTextField();
        ms_jButtonSave = new javax.swing.JButton();
        ms_jPanelList = new javax.swing.JPanel();
        ms_jMenuBar = new javax.swing.JMenuBar();
        ms_jMenuFile = new javax.swing.JMenu();
        ms_jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ms_jLabelInsertWhatDidYouBought.setText("Wpisz co kupiłeś");

        ms_jLabelInsertValue.setText("Podaj wartość");

        ms_jTextFieldInsertValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jTextFieldInsertValueActionPerformed(evt);
            }
        });

        ms_jLabelBoughtType.setText("Typ zakupionego towaru");

        ms_jComboBoxBoughtType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ms_jLabelDateBought.setText("Data zakupu");

        ms_jLabelTodayShopping.setText("Dzisiejsze zakupy");

        ms_jTextAreaTodayShopping.setColumns(20);
        ms_jTextAreaTodayShopping.setRows(5);
        jScrollPane1.setViewportView(ms_jTextAreaTodayShopping);

        ms_jLabelTodayCost.setText("Wydatki z dzisiaj");

        ms_jLabelWeekCost.setText("Wydatki z tygodznia");

        ms_jButtonSave.setText("Zapisz");
        ms_jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ms_jPanelInsertLayout = new javax.swing.GroupLayout(ms_jPanelInsert);
        ms_jPanelInsert.setLayout(ms_jPanelInsertLayout);
        ms_jPanelInsertLayout.setHorizontalGroup(
            ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ms_jLabelInsertWhatDidYouBought)
                            .addComponent(ms_jTextFieldInsertWhatDidYouBought, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ms_jLabelInsertValue)
                            .addComponent(ms_jTextFieldInsertValue, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ms_jLabelTodayShopping))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                        .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ms_jLabelBoughtType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ms_jComboBoxBoughtType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ms_jLabelWeekCost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelInsertLayout.createSequentialGroup()
                                    .addComponent(ms_jLabelDateBought)
                                    .addGap(73, 73, 73))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ms_jPanelInsertLayout.createSequentialGroup()
                                    .addComponent(ms_jTextFieldDateBought, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)))
                            .addComponent(ms_jTextFieldTodayCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ms_jTextFieldWeekCost, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ms_jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                        .addComponent(ms_jLabelTodayCost)
                        .addGap(180, 180, 180))))
        );
        ms_jPanelInsertLayout.setVerticalGroup(
            ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jLabelInsertWhatDidYouBought)
                    .addComponent(ms_jLabelInsertValue)
                    .addComponent(ms_jLabelBoughtType)
                    .addComponent(ms_jLabelDateBought))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jTextFieldInsertWhatDidYouBought, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jTextFieldInsertValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jComboBoxBoughtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jTextFieldDateBought, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jLabelTodayShopping)
                    .addComponent(ms_jButtonSave))
                .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ms_jLabelTodayCost)
                            .addComponent(ms_jTextFieldTodayCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ms_jPanelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ms_jTextFieldWeekCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ms_jLabelWeekCost))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ms_jPanelInsertLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        ms_jTabbedPaneMain.addTab("Wprowadź zakupy", ms_jPanelInsert);

        javax.swing.GroupLayout ms_jPanelListLayout = new javax.swing.GroupLayout(ms_jPanelList);
        ms_jPanelList.setLayout(ms_jPanelListLayout);
        ms_jPanelListLayout.setHorizontalGroup(
            ms_jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        ms_jPanelListLayout.setVerticalGroup(
            ms_jPanelListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        ms_jTabbedPaneMain.addTab("Lista zakupów", ms_jPanelList);

        ms_jMenuFile.setText("File");
        ms_jMenuBar.add(ms_jMenuFile);

        ms_jMenuEdit.setText("Edit");
        ms_jMenuBar.add(ms_jMenuEdit);

        setJMenuBar(ms_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jTabbedPaneMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jTabbedPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_jTextFieldInsertValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jTextFieldInsertValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jTextFieldInsertValueActionPerformed

    private void ms_jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonSaveActionPerformed
        FileUtils stf = new FileUtils();
        String text = ms_jTextFieldInsertWhatDidYouBought.getText()+"; "+ms_jTextFieldInsertValue.getText()+"zł ; "+ms_jComboBoxBoughtType.getSelectedItem().toString()+" ; "+ms_jTextFieldDateBought.getText()+"\n";
        ms_jTextAreaTodayShopping.append(""+ms_jTextFieldInsertWhatDidYouBought.getText()+"; "+ms_jTextFieldInsertValue.getText()+"zł ; "+ms_jComboBoxBoughtType.getSelectedItem().toString()+" ; "+ms_jTextFieldDateBought.getText()+"\n");
        stf.saveToFile(text);
        try {
            FileWriter fw = new FileWriter(file_name, true);
            fw.write(ms_jTextAreaTodayShopping.getText()+"\n");
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger("Blad: "+ex.toString());
        }
        ms_jTextFieldInsertWhatDidYouBought.setText("");
        ms_jTextFieldInsertValue.setText("");
        ms_jTextFieldDateBought.setText("");
    }//GEN-LAST:event_ms_jButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista_zakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista_zakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista_zakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista_zakupow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista_zakupow().setVisible(true);
            }
        });
    }
    private void addKeyListnerToWhatDidYouBought(){
        ms_jTextFieldInsertWhatDidYouBought.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
               char ch = e.getKeyChar();
               if(ch == KeyEvent.VK_SPACE || ch >= 65 && ch <= 90 || ch == KeyEvent.VK_SHIFT || ch == KeyEvent.VK_CAPS_LOCK || ch == KeyEvent.VK_BACK_SPACE || ch >= 97 && ch <= 122){
                   ms_jTextFieldInsertWhatDidYouBought.setEditable(true);
               }else{
                   ms_jTextFieldInsertWhatDidYouBought.setEditable(false);
               }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    private void filljCBProducts(){
        ArticleTypeUtils atu = new ArticleTypeUtils();
        ms_jComboBoxBoughtType.removeAllItems();
        try{
        Scanner sc = new Scanner(produkty);
        String text = "";
        while(sc.hasNext()){
            ms_jComboBoxBoughtType.addItem(sc.nextLine().replace(",", "\n"));
        }
        }catch(FileNotFoundException ex){
            System.out.println("Blad: "+ex);
        }
    }
    private void addKeyListnerToInsertValue(){
        ms_jTextFieldInsertValue.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                String temp = ms_jTextFieldInsertValue.getText();
                String [] splitted = temp.split(",");
                if(temp.contains(",")){
                if(splitted[1].length()<=2){
                if(ch >= '0' && ch <= '9' || ch == KeyEvent.VK_BACK_SPACE){
                    ms_jTextFieldInsertValue.setEditable(true);
                    //System.out.println("Nacisnieto cyfre: "+ch);
                }else{
                    ms_jTextFieldInsertValue.setEditable(false);
                }
                }
            }else{
                    if(ch >= '0' && ch <= '9' || ch == KeyEvent.VK_BACK_SPACE || ch == ','){
                        ms_jTextFieldInsertValue.setEditable(true);
                    }else{
                        ms_jTextFieldInsertValue.setEditable(false);
                    }
                }
            }
            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    private void addtoolTipsToElements(){
        ms_jTextFieldInsertWhatDidYouBought.setToolTipText("<html><h3>Wprowadz tekst</h3><p>Nie uzywaj polskich znakow</p></html>");
        ms_jTextFieldInsertValue.setToolTipText("<html><h3>Wprowadz tekst</h3><p>Nie uzywaj polskich znakow oraz wprowadz wylacznie liczby</p></html>");
        ms_jTextFieldDateBought.setToolTipText("<html><h3>Wprowadz date</h3><p>Uzywaj wylacznie cyfr i kropek</p></html>");
        ms_jComboBoxBoughtType.setToolTipText("<html><h3>Wybierz rzecz</h3></html>");
        ms_jTextAreaTodayShopping.setToolTipText("<html><h3>Tu wyswietla sie twoje zakupy</h3></html>");
        ms_jButtonSave.setToolTipText("<html><h3>Przycisk zapisu</h3></html>");
        ms_jTextFieldTodayCost.setToolTipText("<html><h3>Suma dzisiejszych zakopow</h3></html>");
        ms_jTextFieldWeekCost.setToolTipText("<html><h3>Suma zakopow z tygodnia</h3></html>");
    }
    private void addKeyListnerToInsertDate(){
        ms_jTextFieldDateBought.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                String temp = ms_jTextFieldDateBought.getText();
                char ch = e.getKeyChar();
                if(ch >= '0' && ch <= '9' || ch == KeyEvent.VK_BACK_SPACE || ch == KeyEvent.VK_PERIOD || ch == KeyEvent.VK_SLASH && temp.length()<=10){
                   ms_jTextFieldDateBought.setEditable(true);
                    if((temp.length() == 4 || temp.length() == 7) && ch != KeyEvent.VK_BACK_SPACE ){
                       ms_jTextFieldDateBought.setText(temp+"-");
                    }else{
                        ms_jTextFieldDateBought.setEditable(true);
                    }
                    //System.out.println("Nacisnieto cyfre: "+ch);
                }else{
                     ms_jTextFieldDateBought.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
   private String file_name = "lista_zakupow.csv";
   private String product_names = "product_names.csv";
   private File produkty  = new File("produkty.txt");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ms_jButtonSave;
    private javax.swing.JComboBox<String> ms_jComboBoxBoughtType;
    private javax.swing.JLabel ms_jLabelBoughtType;
    private javax.swing.JLabel ms_jLabelDateBought;
    private javax.swing.JLabel ms_jLabelInsertValue;
    private javax.swing.JLabel ms_jLabelInsertWhatDidYouBought;
    private javax.swing.JLabel ms_jLabelTodayCost;
    private javax.swing.JLabel ms_jLabelTodayShopping;
    private javax.swing.JLabel ms_jLabelWeekCost;
    private javax.swing.JMenuBar ms_jMenuBar;
    private javax.swing.JMenu ms_jMenuEdit;
    private javax.swing.JMenu ms_jMenuFile;
    private javax.swing.JPanel ms_jPanelInsert;
    private javax.swing.JPanel ms_jPanelList;
    private javax.swing.JTabbedPane ms_jTabbedPaneMain;
    private javax.swing.JTextArea ms_jTextAreaTodayShopping;
    private javax.swing.JTextField ms_jTextFieldDateBought;
    private javax.swing.JTextField ms_jTextFieldInsertValue;
    private javax.swing.JTextField ms_jTextFieldInsertWhatDidYouBought;
    private javax.swing.JTextField ms_jTextFieldTodayCost;
    private javax.swing.JTextField ms_jTextFieldWeekCost;
    // End of variables declaration//GEN-END:variables
}
