/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.kalkulator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Dzemor
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }
    
    private void zapiszdzialanie(){
        try{
            if(ms_jCheckBoxMenuItemSaveHistory.isSelected()){
                FileWriter fw = new FileWriter(fileDzialania, true);
                fw.write(ms_WprowadzonaLiczba1+""+ms_rodzajDzialania+""+ms_WprowadzonaLiczba2+"="+ms_wynik+"\n");
                fw.close();
            }
        }catch (IOException ex) {
            System.out.println("Blad: "+ex.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_jPanelMain = new javax.swing.JPanel();
        ms_jLabelTitle = new javax.swing.JLabel();
        ms_jComboBox = new javax.swing.JComboBox<>();
        ms_jTextFieldOutput = new javax.swing.JTextField();
        ms_jTextFieldInput = new javax.swing.JTextField();
        ms_jLabelArrow = new javax.swing.JLabel();
        ms_jButtonCalculate = new javax.swing.JButton();
        ms_jTextFieldInput2 = new javax.swing.JTextField();
        ms_jLabelFirst = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ms_jMenuBar = new javax.swing.JMenuBar();
        ms_jMenuFile = new javax.swing.JMenu();
        ms_jCheckBoxMenuItemSaveHistory = new javax.swing.JCheckBoxMenuItem();
        ms_jMenuItemExit = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jCheckBoxMenuItemHowMuchDays = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");
        setResizable(false);

        ms_jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        ms_jLabelTitle.setText("Kalkulator");

        ms_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proszę wybrać działanie:", "dodawanie", "odejmowanie", "mnożenie", "dzielenie", "potęgowanie", "pierwastkowanie", "kasowanie wyniku", " " }));

        ms_jTextFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jTextFieldInputActionPerformed(evt);
            }
        });

        ms_jLabelArrow.setText("-------->");

        ms_jButtonCalculate.setText("Oblicz");
        ms_jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonCalculateActionPerformed(evt);
            }
        });

        ms_jLabelFirst.setText("Pierwsza liczba");

        jLabel2.setText("Druga liczba(oprócz pierwiastkowania)");

        javax.swing.GroupLayout ms_jPanelMainLayout = new javax.swing.GroupLayout(ms_jPanelMain);
        ms_jPanelMain.setLayout(ms_jPanelMainLayout);
        ms_jPanelMainLayout.setHorizontalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ms_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(ms_jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ms_jTextFieldInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jLabelArrow)
                .addGap(12, 12, 12)
                .addComponent(ms_jTextFieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_jButtonCalculate)
                .addGap(89, 89, 89))
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(ms_jLabelTitle))
                    .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(ms_jLabelFirst)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ms_jPanelMainLayout.setVerticalGroup(
            ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelMainLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ms_jLabelTitle)
                .addGap(80, 80, 80)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jLabelFirst)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ms_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jLabelArrow)
                    .addComponent(ms_jButtonCalculate)
                    .addComponent(ms_jTextFieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_jTextFieldInput2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
        );

        ms_jMenuFile.setText("Plik");

        ms_jCheckBoxMenuItemSaveHistory.setSelected(true);
        ms_jCheckBoxMenuItemSaveHistory.setText("Zapisz historię działań");
        ms_jMenuFile.add(ms_jCheckBoxMenuItemSaveHistory);

        ms_jMenuItemExit.setText("Zamknij");
        ms_jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jMenuItemExitActionPerformed(evt);
            }
        });
        ms_jMenuFile.add(ms_jMenuItemExit);

        ms_jMenuBar.add(ms_jMenuFile);

        jMenuTools.setText("Narzędzia");

        jCheckBoxMenuItemHowMuchDays.setSelected(true);
        jCheckBoxMenuItemHowMuchDays.setText("Ile dni pomiędzy datami");
        jCheckBoxMenuItemHowMuchDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemHowMuchDaysActionPerformed(evt);
            }
        });
        jMenuTools.add(jCheckBoxMenuItemHowMuchDays);

        ms_jMenuBar.add(jMenuTools);

        setJMenuBar(ms_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jPanelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ms_jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jMenuItemExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ms_jMenuItemExitActionPerformed

    private void ms_jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonCalculateActionPerformed
        ms_jTextFieldOutput.setText("");
        ms_WybranaJednostka = ms_jComboBox.getSelectedIndex();
        System.out.println(ms_WybranaJednostka);
        switch(ms_WybranaJednostka){
             case 1:
               ms_rodzajDzialania = "+";
               ms_WprowadzonaLiczba1 = Integer.parseInt(ms_jTextFieldInput.getText());
               ms_WprowadzonaLiczba2 = Integer.parseInt(ms_jTextFieldInput2.getText());
               ms_wynik = ms_WprowadzonaLiczba1 + ms_WprowadzonaLiczba2;
               ms_jTextFieldOutput.setText(String.valueOf(ms_wynik));
               zapiszdzialanie();
               break;
            case 2:
               ms_rodzajDzialania = "-";
               ms_WprowadzonaLiczba1 = Integer.parseInt(ms_jTextFieldInput.getText());
               ms_WprowadzonaLiczba2 = Integer.parseInt(ms_jTextFieldInput2.getText());
               ms_wynik = ms_WprowadzonaLiczba1 - ms_WprowadzonaLiczba2;
               ms_jTextFieldOutput.setText(String.valueOf(ms_wynik));
               zapiszdzialanie();
               break;
            case 3:
               ms_rodzajDzialania = "*";
               ms_WprowadzonaLiczba1 = Integer.parseInt(ms_jTextFieldInput.getText());
               ms_WprowadzonaLiczba2 = Integer.parseInt(ms_jTextFieldInput2.getText());
               ms_wynik = ms_WprowadzonaLiczba1 * ms_WprowadzonaLiczba2;
               ms_jTextFieldOutput.setText(String.valueOf(ms_wynik));
               zapiszdzialanie();
               break;
            case 4:
               ms_rodzajDzialania = "/";
               ms_WprowadzonaLiczba1 = Integer.parseInt(ms_jTextFieldInput.getText());
               ms_WprowadzonaLiczba2 = Integer.parseInt(ms_jTextFieldInput2.getText());
               ms_wynik = ms_WprowadzonaLiczba1 / ms_WprowadzonaLiczba2;
               ms_jTextFieldOutput.setText(String.valueOf(ms_wynik));
               zapiszdzialanie();
               break;
            case 5:
               ms_rodzajDzialania = "*";
               ms_WprowadzonaLiczba1 = Integer.parseInt(ms_jTextFieldInput.getText());
               ms_WprowadzonaLiczba2 = Integer.parseInt(ms_jTextFieldInput2.getText());
               ms_wynik = (int) Math.pow(ms_WprowadzonaLiczba1, ms_WprowadzonaLiczba2);
               ms_jTextFieldOutput.setText(String.valueOf(ms_wynik));
               zapiszdzialanie();
               break;
            case 6:
               ms_rodzajDzialania = " pierwiastek ";
               ms_WprowadzonaLiczba1 = Integer.parseInt(ms_jTextFieldInput.getText());
               ms_wynik  = (int) Math.sqrt(ms_WprowadzonaLiczba1);
               ms_jTextFieldOutput.setText(String.valueOf(ms_wynik));
               zapiszdzialanie();
               break;
            case 7:
               ms_jTextFieldOutput.setText("");
               ms_jTextFieldInput2.setText("");
               ms_jTextFieldInput.setText("");
               break;
            default:
               System.out.println("Nie ma takiej opcji!!");
               break;
        }
    }//GEN-LAST:event_ms_jButtonCalculateActionPerformed

    private void ms_jTextFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jTextFieldInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jTextFieldInputActionPerformed

    private void jCheckBoxMenuItemHowMuchDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemHowMuchDaysActionPerformed
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MM yyyy");
        JOptionPane.showInputDialog("Wprowadź datę w formacie dd mm yyyy np: 01 02 2021");
        
    }//GEN-LAST:event_jCheckBoxMenuItemHowMuchDaysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }
    int ms_WybranaJednostka;
    String ms_rodzajDzialania;
    String ms_wprowadzoneDzialanie1;
    String ms_wprowadzoneDzialanie2;
    int ms_WprowadzonaLiczba1;
    int ms_WprowadzonaLiczba2;
    int ms_wynik;
    File fileDzialania  = new File("dzialania.txt");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemHowMuchDays;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JButton ms_jButtonCalculate;
    private javax.swing.JCheckBoxMenuItem ms_jCheckBoxMenuItemSaveHistory;
    private javax.swing.JComboBox<String> ms_jComboBox;
    private javax.swing.JLabel ms_jLabelArrow;
    private javax.swing.JLabel ms_jLabelFirst;
    private javax.swing.JLabel ms_jLabelTitle;
    private javax.swing.JMenuBar ms_jMenuBar;
    private javax.swing.JMenu ms_jMenuFile;
    private javax.swing.JMenuItem ms_jMenuItemExit;
    private javax.swing.JPanel ms_jPanelMain;
    private javax.swing.JTextField ms_jTextFieldInput;
    private javax.swing.JTextField ms_jTextFieldInput2;
    private javax.swing.JTextField ms_jTextFieldOutput;
    // End of variables declaration//GEN-END:variables
}
